Fixed typos in Agents groups section (#899)
* Update master branch (#876)

* Update version to 3.8

* Merge 3.7 branch into 3.8 branch (#751)

* Key polling wodle documentation (#741)

* Add documentation about check_perm and check_attrs options (#653)

* Adding new internal_option documentation for ossec-remoted (#714)

* Deprecate FIM option remove_old_diff (#659)

* Corrected spelling mistake (#775)

* Make FIM alert new files by default (#772)

* Add documentation for follow_symbolic_link attribute (#769)

* Remove only-upgrade flag from upgrading guides (#766)

* Updated register agents documentation (#758)

* Added email_log_source label (#760)

* Update allowed queue_size values for key polling wodle (#780)

* Update vuln-detector documentation (#748)

* Add the release version of check_attr and check_perm (#782)

* Remove attributes that are not in the decoders (#781)

* Added new Wazuh Kibana app config file setting (#765)

* Fix typos (#783)

* Remove note about Wazuh 2.1.1 (#757)

* Review documentation images folder (#744)

* Reviewed documentation images folder

* Reduce size of images folder

* Minor documentation typo fixes (#767)

* Fix typo in Ansible documentation

* Fix wrong path in OpenSCAP reference documentation

* Fix code highlight

* Fixed bad references in Email alerts section

* Remove "string" value from "type" attribute in Syscheck "ignore" tag

* Rework AWS documentation (#778)

* Update version to 3.8

* Add documentation for AWS Inspector (#670)

* Add new AWS services (#671)

* Merge 3.7 branch into 3.8 branch (#751)

* Added initial AWS rework files

* Cloudtrail - Initial commit

* Adding more AWS services (in progress)

* Added troubleshooting and configuration sections

* Finished documentation restructuring

* Minor adjustments for AWS docs

* Reduced unnecessary headings

* Replacing old text - Credentials documentation changes

* Replaced some configurations with aws profiles

* Added note about AWS S3 config reference

* Moved use cases to services

* Added more descriptions for some AWS docs sections

* Revert "Rework AWS documentation (#778)" (#785)

This reverts commit ff732e94a20522e49ff98c0b3390a28a49f35a2f.

* Logcollector extension for Windows Eventchannel (#660)

* API installation guide (sources) was updated. (#788)

* Add Eventchannel enhancement to 3.8.0 release-notes (#754)

* Merge contents from "3.7" into "3.8" (#790)

* Rework AWS documentation (#786)

* Update for VPC configuration (#793)

* Considerations of configuration (region parameter) for Inspector were updated. (#796)

* Update API reference for 3.8.0 (#795)

* Update API reference for 3.8

* Update reference.rst

* Update documentation and version selector for 3.8.0 (#791)

* 3.7 - Update version selector

* Fixing typo in default azure configuration (#806)

* fix-azure-typo (#807)

* Fix Windows agent checksums (#808)

* New Wazuh app documentation (#656)

* Adding tutorial to change name of Elasticsearch indices

* Minor adjustments to existing Wazuh app documents

* Remove unnecessary note

* Minor adjustments and typofixes

* Update guide for custom indices names

* Fux some typos

* Revert "3.7 - Update version selector" (#809)

* Update syslog-output.rst (#811)

Updated the documentation for server to include IP address OR hostname

* Fix Java link

* Removed wrong curl parameters

* Fix OVA, OVF sums

* Update syslog-output.rst (#814)

Clarified that group here refers to rule group and not agent group.

* Update integration.rst (#815)

Updated to indicate group here refers to rule group and not agent group.

* Search Guard guide (#759)

* Added Search Guard guide (in progress)

* Adapted to full admin plus 6.5.4

* Fixed roles

* Fix Kibana steps

* Added login screenshot

* Modified Search Guard screenshot

* Some grammar changes

* Fix typo

* Fix typo

* Fix typo

* Fix code-block

* Minor changes

* Fix list

* Added 3.8.0 release notes (#810)

* Added 3.8.0 release notes

* Fix code-block format

* Minor changes for 3.8 release notes

* Fix typo

* Added screenshot for Windows new alerts

* Fix typo

* Replaced screenshot

* Changed titles and screenshots

* Fix typo (#818)

* Fix typo (#819)

* Updated checksums

* Updated OVA, OVF, VMDK checksums

* Added missing checksums

* Updated WPK checksums

* Updated Copyright year

* Updated checksums

* Fix typo (OVA link)

* Fix typo

* Fix typo

* Add wazuh module version (#833)

* Update install-ansible.rst (#832)

* Update wazuh-container.rst (#831)

*  Revert msi package (#839)

* Revert msi package

* Changed checksum

* Prepare release v3.8.1 (#842)

* Bump version 3.8.1

* Updated release notes for 3.8.1

* Fix typo

* Added some package sums

* Added OVA sums

* Added Wazuh apps sums

* Added checksums

* Fixed checksums positions

* Update release_3_8_1.rst

* Added Solaris 10 sparc sum

* Added WPK sums

* Fix typo

* Added VMDK sum

* minor grammar corrections (#851)

* Wazuh-Ansible link points to tag (#841)

* 3.8 - Clarify agent group v3.7.0 (#872)

* Bump version (3.8.2) (#875)

* Bump version (3.8.2)

* Added release notes for 3.8.2

* Bump version in API reference examples

* Added checksums

* Added a few modifications in 3.8.2 release notes

* Added missing checksums

* Update reference.rst to fix the compilation errors

/root/wazuh-documentation/source/user-manual/api/reference.rst:11: ERROR: Unknown target name: "active response".
/root/wazuh-documentation/source/user-manual/api/reference.rst:32: ERROR: Unknown target name: "active response".

Fixed those errors.

* Update centralized-configuration.rst

* Update elastic_server_rpm.rst

* Update different_major.rst

* Update reference.rst

* Update grouping-agents.rst